### ISSUE TITLE
Prometheus yml file added node exporter ip details,each time server provisioning time . we are doing details to  prometheus yml.

### ISSUE THREAD

**Issue by babujii** [dbluxo/quickstart-thanos#102]
Prometheus yml file added node exporter ip details,each time servers provisioning node-exporter ip. we are adding node exporter details to  prometheus yml and restarting docker container. Do we have any option without restart prometheus service. Node exporter should update in the prometheus yml file.

**Comment by dbluxo** [comment]
You can have Prometheus reload the configuration after config changes to prometheus.yml via a reload handler:  https://www.robustperception.io/reloading-prometheus-configuration This project has no automatism for this.
