### ISSUE TITLE
 Grafana dashboard configuration Post "http://localhost:9090/api/v1/query" : dial tcp [::1]:9090: connect: connection refused

### ISSUE THREAD

**Issue by quangnb-01182** [dbluxo/quickstart-thanos#160]
i'm a new user and how can i configure grafana's DATA SOURCE (dashboard) ? i tried http://thanos-query:9090/ and http://localhost:10901/ however it has error message : 
Error reading Prometheus: Post "http://localhost:9090/api/v1/query" : dial tcp [::1]:9090: connect: connection refused

**Comment by dbluxo** [comment]
Please read how to add a Grafana data soruce in the official documentation: https://grafana.com/docs/grafana/latest/datasources/add-a-data-source/
