### ISSUE TITLE
Prometheus Container is restarting again and again

### ISSUE THREAD

**Issue by benzengin** [dbluxo/quickstart-thanos#164]
Prometheus Container is restarting again and again. Docker logs saying:
caller=main.go:438 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus1.yaml)" file=/etc/prometheus/prometheus1.yaml err="open /etc/prometheus/prometheus1.yaml: permission denied"

**Comment by dbluxo** [comment]
This seems to be a local problem with permissions, I can't help you there.
